USE  basic_sql_case_study
SELECT * FROM CUSTOMER
SELECT * FROM TRANSACTIONS
SELECT * FROM PROD_CAT_INFO

-- DATA PREPARATION AND UNDERSTANDING
--1. What is total number of rows in each of the 3 tables in the database?
SELECT COUNT(CUSTOMER_ID) TABLE_COUNT, 'CUSTOMER' AS TABLE_NAME FROM CUSTOMER
UNION ALL
SELECT COUNT(CUST_ID), 'TRANSACTION' FROM TRANSACTIONS
UNION ALL
SELECT COUNT(PROD_CAT_CODE), 'PRODUCT CATEGORY' FROM PROD_CAT_INFO

--2. What is the total number of transactions that have a return?
SELECT COUNT(QTY) AS COUNT_OF_RETURN_TRANSACTION FROM TRANSACTIONS
WHERE SIGN(TOTAL_AMT) = '-1'

----------(OR)----------

SELECT COUNT(QTY) AS COUNT_OF_RETURN_TRANSACTION FROM TRANSACTIONS
WHERE QTY < 0

--3. Convert the date variables into valid date formats before proceeding ahead?
SELECT FORMAT (PARSE (TRAN_DATE AS DATE USING 'AR-LB'), 'dd-MM-yyyy') AS CORRECT_DATE FROM TRANSACTIONS
SELECT FORMAT (PARSE (DOB AS DATE USING 'AR-LB'), 'dd-MM-yyyy') AS CORRECT_DOB FROM CUSTOMER

--4. What is the time range of the transaction data available for analysis? Show the output in number of 
--   days, months and years simultaneously in different columns?
SELECT MIN(PARSE(TRAN_DATE AS DATE USING 'AR-LB')) AS START_DATE,
MAX(PARSE(TRAN_DATE AS DATE USING 'AR-LB')) AS END_DATE,
DATEDIFF(DAY,MIN(PARSE(TRAN_DATE AS DATE USING 'AR-LB')),MAX(PARSE(TRAN_DATE AS DATE USING 'AR-LB'))) AS NO_OF_DAYS,
DATEDIFF(MONTH,MIN(PARSE(TRAN_DATE AS DATE USING 'AR-LB')),MAX(PARSE(TRAN_DATE AS DATE USING 'AR-LB'))) AS NO_OF_MONTH,
DATEDIFF(YEAR,MIN(PARSE(TRAN_DATE AS DATE USING 'AR-LB')),MAX(PARSE(TRAN_DATE AS DATE USING 'AR-LB'))) AS NO_OF_YEAR FROM TRANSACTIONS

--5.Which product category does the sub-category "DIY" belong to
SELECT PROD_CAT, PROD_SUBCAT FROM PROD_CAT_INFO
WHERE PROD_SUBCAT='DIY'

-- DATA ANALYSIS
--1. Which channel is most frequently use for transaction?
SELECT TOP 1 (STORE_TYPE), COUNT(STORE_TYPE) NO_OF_TRANSACTION FROM TRANSACTIONS
GROUP BY STORE_TYPE
ORDER BY COUNT(STORE_TYPE) DESC

--2. What is the count of the male and female customers in the database?
SELECT GENDER, COUNT(GENDER)  AS COUNT_OF_GENDER FROM CUSTOMER
WHERE GENDER IN ('M', 'F')
GROUP BY GENDER

--3. From which city do we have maximum number of customers and how many?
SELECT TOP 1 CITY_CODE, COUNT(CUSTOMER_ID) AS MAX_NO_OF_CUSTOMERS FROM CUSTOMER
GROUP BY CITY_CODE
ORDER BY COUNT(CUSTOMER_ID) DESC

--4. How many sub-categories are there under the books category?
SELECT PROD_CAT, COUNT(PROD_SUBCAT) AS COUNT_OF_SUBCATEGORY FROM PROD_CAT_INFO
WHERE PROD_CAT = 'BOOKS'
GROUP BY PROD_CAT

--5. What is the maximum quantity of products ever ordered?
SELECT MAX(QTY) MAX_QTY_OF_PROD FROM TRANSACTIONS
--(OR)
SELECT TOP 1 T2.PROD_CAT PRODUCT, COUNT(T1.QTY) MAX_QTY_OF_PROD FROM TRANSACTIONS T1
INNER JOIN PROD_CAT_INFO T2 ON T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
GROUP BY PROD_CAT
ORDER BY COUNT(T1.QTY) DESC

--6. What is the net total revenue generated in categories Electronics and Books?
SELECT T2.PROD_CAT,  SUM(T1.TOTAL_AMT) AS TOTAL_REVENUE FROM TRANSACTIONS T1
FULL JOIN PROD_CAT_INFO T2 ON T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
WHERE PROD_CAT IN('ELECTRONICS', 'BOOKS')
GROUP BY PROD_CAT

--7. How many customers have >10 transactions with us, excluding returns?
SELECT T1.CUSTOMER_ID, COUNT(T2.TRANSACTION_ID) COUNT_OF_TRANSACTION FROM CUSTOMER T1
INNER JOIN TRANSACTIONS T2 ON T1.CUSTOMER_ID = T2.CUST_ID
WHERE TOTAL_AMT > 0
GROUP BY CUSTOMER_ID
HAVING COUNT(T2.TRANSACTION_ID)>10


--8. What is the combined revenue earned from the "Electronics" & "Clothing" categories, from "Flagship stores"
SELECT SUM(T2.TOTAL_AMT) AS COMBINED_REVENUE FROM PROD_CAT_INFO T1
INNER JOIN TRANSACTIONS T2 ON T1.PROD_CAT_CODE= T2.PROD_CAT_CODE AND T1.PROD_SUB_CAT_CODE= T2.PROD_SUBCAT_CODE
WHERE T2.STORE_TYPE IN ('FLAGSHIP STORE') AND T1.PROD_CAT IN ('ELECTRONICS', 'CLOTHING')


--9. What is the total revenue generated from "Male" customers in "Electronics" category?
--   Output Should display total revenue by prod sub-cat
SELECT T3.PROD_SUBCAT AS ELECTRONICS_CATEGORY, SUM(T2.TOTAL_AMT) AS REVENUE FROM CUSTOMER T1
LEFT JOIN TRANSACTIONS T2 ON T1.CUSTOMER_ID = T2.CUST_ID
LEFT JOIN PROD_CAT_INFO T3 ON T2.PROD_SUBCAT_CODE = T3.PROD_SUB_CAT_CODE AND T2.PROD_CAT_CODE = T3.PROD_CAT_CODE
WHERE T1.GENDER = 'M' AND T3.PROD_CAT = 'ELECTRONICS'
GROUP BY GENDER, PROD_SUBCAT
SELECT T3.PROD_CAT AS TOTAL, SUM(T2.TOTAL_AMT) AS TOTAL_REVENUE FROM CUSTOMER T1
LEFT JOIN TRANSACTIONS T2 ON T1.CUSTOMER_ID = T2.CUST_ID
LEFT JOIN PROD_CAT_INFO T3 ON T2.PROD_SUBCAT_CODE = T3.PROD_SUB_CAT_CODE AND T2.PROD_CAT_CODE = T3.PROD_CAT_CODE
WHERE T1.GENDER = 'M' AND T3.PROD_CAT = 'ELECTRONICS'
GROUP BY GENDER, PROD_CAT

--10. What is percentage of sales and return by product sub category; display only top 5 sub category in terms of sales?
SELECT DISTINCT TOP 5 T2.PROD_SUBCAT, SUM(T1.TOTAL_AMT) AS SUBCAT_TOTAL_REVENUE, ROUND(SUM(T1.TOTAL_AMT)/SUM(SUM(TOTAL_AMT)) OVER() ,2)*100 AS PERCENT_AGE FROM TRANSACTIONS T1
INNER JOIN PROD_CAT_INFO T2 ON T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
WHERE QTY > 0
GROUP BY PROD_SUBCAT
ORDER BY SUM(TOTAL_AMT) DESC


--11. For all customers aged between 25 to 35 years find what is the net total revenue generated by these 
--    consumers in last 30 days of transactions from max transaction date available in the data?
DECLARE @MAXDATE1 DATETIME
SELECT @MAXDATE1 = MAX(CONVERT(DATETIME,TRAN_DATE,103)) FROM TRANSACTIONS T1
SELECT SUM(TOTAL_AMT) AS TOTAL_REVENUE FROM CUSTOMER T2
INNER JOIN TRANSACTIONS T1 ON T2.CUSTOMER_ID = T1.CUST_ID
WHERE DATEDIFF(YEAR, (CONVERT(DATETIME, DOB, 103)), (CONVERT(DATETIME, TRAN_DATE, 103))) BETWEEN 25 AND 35 AND CONVERT(DATETIME, TRAN_DATE,103) >= DATEDIFF(DAY, 30, @MAXDATE1)

--12. Which product category has seen the max value f returns in the last 3 months of transactions?

--13. Which store-type sells the maximum products; by value of sales amount and by quantity sold?
SELECT DISTINCT TOP 1 T1.STORE_TYPE, SUM(T1.TOTAL_AMT) AS REVENUE, SUM(T1.QTY) AS QTY FROM PROD_CAT_INFO T2
INNER JOIN TRANSACTIONS T1 ON T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
GROUP BY STORE_TYPE
ORDER BY SUM(TOTAL_AMT) DESC

--14. What are the categories for which average revenue is above the overall average?
SELECT T1.PROD_CAT, AVG(T2.TOTAL_AMT) AS AVERAGE_REVENUE FROM TRANSACTIONS T2
LEFT JOIN PROD_CAT_INFO T1 ON T2.PROD_CAT_CODE = T1.PROD_CAT_CODE
GROUP BY T1.PROD_CAT
HAVING AVG(TOTAL_AMT) > (SELECT AVG(TOTAL_AMT) FROM TRANSACTIONS)
ORDER BY AVG(T2.TOTAL_AMT) DESC

--15. Find the average and total revenue by each subcategory for the catgories which are amoung top 5 categories in terms of quantity sold.
SELECT DISTINCT TOP 5  T2.PROD_SUBCAT, SUM(T1.QTY) AS QUANTITY, AVG(T1.TOTAL_AMT) AS AVERAGE_REVENUE, SUM(T1.TOTAL_AMT) AS TOTAL_REVENUE FROM TRANSACTIONS T1
INNER JOIN PROD_CAT_INFO T2 ON T1.PROD_SUBCAT_CODE = T2.PROD_SUB_CAT_CODE AND T1.PROD_CAT_CODE = T2.PROD_CAT_CODE
GROUP BY PROD_SUBCAT
ORDER BY SUM(T1.QTY) DESC